basic.forever(function () {
    led.plot(0, 0)
    led.plot(0, 1)
    led.plot(0, 2)
    led.plot(0, 3)
    led.plot(0, 4)
    led.plot(1, 0)
    led.plot(1, 1)
    led.plot(1, 2)
    led.plot(1, 3)
    led.plot(1, 4)
    led.plot(2, 0)
    led.plot(2, 1)
    led.plot(2, 2)
    led.plot(2, 3)
    led.plot(2, 4)
})
